### ISSUE TITLE
Python3 unicode/bytes in argv.

### ISSUE THREAD

**Issue by wapiflapi** [pexpect/pexpect#188] opened 2015-03-16 18:32 UTC
I want to pass bytes to the underlying `os.exec*()` calls. Currently pexpect doesn't handle this well because `which()` and the construction of `self.name` aren't compatible with bytes in python3. There might  also be other bugs I haven't found yet.

Would you be interested in a pull request fixing those issues or should I wait with this until #182 is merged and fix this afterwards?

**Comment by jquast** [comment] 2015-03-18 16:23
You can base off that branch if you like, we do intend to merge it soon.

**Comment by jquast** [comment] 2015-09-21 20:03
Created PR #265 for the requested test cases, this works in master and next pexpect 4.0 release, closing not a bug

**Closed by jquast** 2015-09-21 20:03 UTC
Labels: bug, needs-code, needs-tests
