### ISSUE TITLE
4.0: PID Exception

### ISSUE THREAD

**Issue by erikb85** [pexpect/pexpect#271] opened 2015-10-05 13:12 UTC
## Gratz to 4.0

Had to say this first. Took some time, now it got automatically installed. Nice! :+1: 

## Error when using pxssh

We tried to use pxssh as usual and immediately got an error message. Have a look. I can provide further details to help analysing it (maybe, this system is under heavy use), but I can't help debugging any more.

```
(MONK) jenkins@prueflab:/var/lib/jenkins/jobs/Regression_Hipox_MS/workspace/MONK$ python
Python 3.4.2 (default, Jun 19 2015, 11:34:49)
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pexpect.pxssh import pxssh
>>> p = pxssh()
>>> p.login("172.29.29.147", "root", "password")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/lib/jenkins/jobs/Regression_Hipox_MS/workspace/MONK/lib/python3.4/site-packages/pexpect/pxssh.py", line 310, in login
    raise ExceptionPxssh('password refused')
pexpect.pxssh.ExceptionPxssh: password refused
>>> p.login("172.29.29.147", "root", "password")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/lib/jenkins/jobs/Regression_Hipox_MS/workspace/MONK/lib/python3.4/site-packages/pexpect/pxssh.py", line 279, in login
    spawn._spawn(self, cmd)
  File "/var/lib/jenkins/jobs/Regression_Hipox_MS/workspace/MONK/lib/python3.4/site-packages/pexpect/pty_spawn.py", line 273, in _spawn
    assert self.pid is None, 'The pid member must be None.'
AssertionError: The pid member must be None.
>>>
KeyboardInterrupt
```

Normal `ssh` to the IP address works.

**Comment by takluyver** [comment] 2015-10-05 17:02
The second error is because pxssh doesn't like `login()` being called more than once per instantiation. I don't think that's a regression.

The first error suggests that something is going wrong with sending or receiving the password. I can use pxssh OK, but the box I have to test it with doesn't need a password.

Can you log the traffic exchanged to provide more clues about what's going on? It should work something like this:

```
logio = io.BytesIO()
p = pxssh(logfile=logio)
p.login(...)
print(logio.getvalue())
```

**Comment by erikb85** [comment] 2015-10-06 12:55
It must contain some side effects that I haven't mentioned because I don't have the knowledge to know them. Now I can't reproduce it either. The system is usually under heavy load, so it is possible that it was running into some system limitations like not enough RAM, too many open ssh connections, etc.

If it's not possible to guess from the surrounding of the code what might result in `self.pid` not being None at this point, then I'd say we close the issue as "not reproducible" and keep it in the back of our heads until we get the error again. At least now I know what additional information I can provide if I get that again.

**Comment by takluyver** [comment] 2015-10-06 13:20
I'm pretty sure the "The pid member must be None." error is just because you've called `p.login()` twice on the same object. The "password refused" error could well be something to do with the conditions you mention, though.

**Comment by takluyver** [comment] 2015-10-06 13:20
Closing this for now, as you suggest :-)

**Closed by takluyver** 2015-10-06 13:20 UTC

**Comment by vjcharlie** [comment] 2015-12-16 04:55
I am having the same issue "password refused" when doing s.login( FQDN, USERNAME, PASSWORD) , look that I am passing variables... it is weird because when I hard code the password instead of using the variable it works fine... but obviously I need to pass a variable and it throws that same error

**Comment by takluyver** [comment] 2015-12-16 09:30
@vjcharlie the only logical explanation I can think of for that is because the password variable does not contain the exact same characters as your hardcoded password. Maybe there are trailing spaces, or encoding differences? Try doing `print(repr(PASSWORD))` just before that line to see what it contains.

Pexpect has no idea whether an argument you pass it came from a variable or a hardcoded string, so if it's doing something different, it must be because the data is different.
