### ISSUE TITLE
pip install pexpect fails for python2

### ISSUE THREAD

**Issue by JaviMerino** [pexpect/pexpect#296] opened 2015-11-02 08:31 UTC
`async.py` uses `yield from` which is only present in python3.  `pip install` fails with:

    # pip install pexpect
    Downloading/unpacking pexpect
    Downloading pexpect-4.0.1.tar.gz (143kB): 143kB downloaded
    Running setup.py (path:/tmp/pip-build-gS7W_o/pexpect/setup.py) egg_info for package pexpect

    Downloading/unpacking ptyprocess>=0.5 (from pexpect)
    Downloading ptyprocess-0.5.tar.gz
    Running setup.py (path:/tmp/pip-build-gS7W_o/ptyprocess/setup.py) egg_info for package ptyprocess

    Installing collected packages: pexpect, ptyprocess
    Running setup.py install for pexpect
          File "/usr/local/lib/python2.7/dist-packages/pexpect/async.py", line 16
            transport, pw = yield from asyncio.get_event_loop()\
                                     ^
        SyntaxError: invalid syntax

    Running setup.py install for ptyprocess

    Successfully installed pexpect ptyprocess
    Cleaning up...

**Comment by takluyver** [comment] 2015-11-02 09:15
Duplicate of #290. It installs OK, even though you see an error (it says `Successfully installed pexpect ptyprocess` at the end), and that module is only loaded if you're using the asyncio integration, so it's not a problem. Apparently if you upgrade pip, you'll no longer see the error.

**Closed by takluyver** 2015-11-02 09:15 UTC

**Comment by JaviMerino** [comment] 2015-11-05 09:43
As @ygbourhis says in #290, it's not enough for people packaging pexpect for distributions.  I'll reopen #290.
