### ISSUE TITLE
Process stops logging after last `expect`

### ISSUE THREAD

**Issue by stephenfin** [pexpect/pexpect#90] opened 2014-07-08 10:08 UTC
If I `spawn` a new child process and `expect` something, I get logging output. However, once this `expect` has been hit, logging stops. The child process has not been killed, or `close`d, and it continues to run in the background and I imagined the logging should continue asynchronously, if you will.

Is this by design, or a bug? If the former, is there any way to get logging to continue while the process exists (i.e. redirect the child process' `stdout` to the console)?

Some (unfortunately long) sample code to demonstrate this:

```bash
#!/usr/bin/env bash
#
# Generate text periodically

while [ 1 ]; do
    echo "This is some text" | tee -a output.log
    sleep 1
done
```

```python
#!/usr/bin/env python
#
# Call 'generate.sh' using pexpect

import pexpect
import os
import sys
import time

SHELL_CMD = ['/bin/bash', '-c']
ROOT_DIR = os.path.dirname(os.path.realpath(__file__))
SCRIPT_CMD = os.path.join(ROOT_DIR, 'generate.sh')

def main():
    cmd = SHELL_CMD + ['"%s"' % SCRIPT_CMD]
    cmd = ' '.join(cmd)

    child = pexpect.spawn(cmd, timeout=10)
    child.logfile_read = sys.stdout

    for i in range(0, 5):
        print('iteration %d' % i)
        try:
            child.expect(['This is some text'])
        except Exception as exc:
            print('error occured')
            raise exc

    time.sleep(1000)

main()
```

The `child` continues to execute. Here's the `stdout` upon killing after ~10 seconds:

```
$ ./run.py
iteration 0
This is some text
iteration 1
This is some text
iteration 2
This is some text
iteration 3
This is some text
iteration 4
This is some text
^CTraceback (most recent call last):
  File "./run.py", line 31, in <module>
    main()
  File "./run.py", line 29, in main
    time.sleep(1000)
KeyboardInterrupt
```

The contents of `output.log` after the same (notice how many `This is some text` lines there are == process still running):

```
This is some text
This is some text
This is some text
This is some text
This is some text
This is some text
This is some text
This is some text
This is some text
This is some text
```

**Comment by jquast** [comment] 2015-09-21 01:17
Marking as duplicate of #54. Otherwise submit a PR for a self-answering FAQ entry to reduce the misunderstanding of expect pull operation

**Closed by jquast** 2015-09-21 01:17 UTC
Labels: docfix, WIP
