### ISSUE TITLE
fdexpect no longer handles serial port file descriptors

### ISSUE THREAD

**Issue by jhps** [pexpect/pexpect#351] opened 2016-06-03 17:03 UTC
When fdexpect was changed to be a subclass of spawnbase rather than spawn it lost the ability to handle file descriptors that are in non-blocking mode.

e.g.:

fd = os.open("/dev/ttyS0", os.O_NONBLOCK|os.O_RDWR|os.O_NOCTTY)
th = pexpect.fdpexpect.fdspawn(fd)
th.expect(["stuff", pexpect.TIMEOUT],5):

No longer works.

I would consider this a major regression. This was a common low overhead way of handling serial ports or sockets.

**Comment by takluyver** [comment] 2016-06-03 17:25
For the record: the complexity here is handling non-blocking fds in a way that doesn't break Windows compatibility.

In the meantime, people who need the old behaviour are welcome to install pexpect 3.x.

**Comment by MountainRider** [comment] 2016-06-28 14:21
If you are not going to fix this, then please change the documentation so that it no longer says

> This is like pexpect, but it will work with any file descriptor that you
pass it. You are reponsible for opening and close the file descriptor.
This allows you to use Pexpect with sockets and named pipes (FIFOs).

**Comment by takluyver** [comment] 2016-06-28 15:17
@jquast any thoughts on what to do for this (and #356)? I feel bad that we've broken things people were doing with fdspawn, but I really don't want to make it inherit from the pty spawn class, and now that it works on Windows, I think it's important to preserve that too.

Maybe we should just say:

- If you have legacy code that broke with Pexpect 4, downgrade to Pexpect 3.x (`pip install pexpect<4`)
- If you're writing new code, use [streamexpect](https://github.com/digidotcom/python-streamexpect) instead of pexpect.

**Comment by MountainRider** [comment] 2016-06-28 17:25
@takluyver: I'm confused. Are you saying you broke POSIX support for [fdspawn](https://github.com/pexpect/pexpect/blob/master/pexpect/fdpexpect.py) so that it would work on Windows? And you are unwilling to make the simple change to detect that the platform is POSIX and override read_nonblocking with a version that uses [select](https://docs.python.org/2/library/select.html)? Please help me understand.

**Comment by takluyver** [comment] 2016-06-28 17:42
I didn't deliberately break POSIX support for fdspawn. I refactored it so that the simpler fdspawn class was not needlessly inheriting from the more complex spawn class. This also meant that it can be used on Windows.

We could do a platform check and reintroduce the more complicated read_nonblocking in fdspawn, but that means more complexity, more code that I can't easily test (and so am liable to break), and an API difference in what fdspawn works with between POSIX and Windows. And I'm not really that interested in Pexpect. I wish I hadn't tried to refactor it for version 4 and had just encouraged people who wanted extra features to make/use something new like streamexpect.

**Comment by MountainRider** [comment] 2016-06-28 19:47
I have a [pull request](https://github.com/pexpect/pexpect/pull/359) that implements the POSIX check in an overridden `read_nonblocking` and includes tests that verify the change. The tests connect to the telnet port on rainmaker.wunderground.com. If you are not behind a firewall that blocks outbound telnet connections, you should be able to run the tests.

**Comment by jquast** [comment] 2016-06-28 21:52
quick thoughts,

- I want to continue the 'fdspawn inherits spawnbase', keeping our pexpect-4 api change
- too many benefits -- because instead of adopting new features, we can suggest to derive and modify, and this proper inheritance model of spawnbase allows it.

- redirecting people to streamexpect is pretty OK... so long as the author agrees to the PR to add such suggestion to our readme.

- Regarding #356, ``sendcontrol()`` gone missing: Whoops! Let's just bring it back, even if it is duplication.

- This issue, ``read_nonblocking()`` going missing: Whoops! Let's also bring that back.

So this is a +1 for @MountainRider's contribution, suggest:

- I'd like tests to run in airplane mode. Suggest to make a simple socket server that does "Hello, press any key", read(1), then "goodbye" should exercise the client API just as well as rainmaker is.

(Though I like both rainmaker and telnet protocol very much!)

- test_interrupt has a 5 second sleep, can we use a kind of semaphore to avoid this?

**Comment by MountainRider** [comment] 2016-06-28 22:21
@jquast: Roger that. I will improve the test cases. Your feedback is very welcome. I can write a socket server. I think an Event will solve the problem where I used the sleep.

**Comment by bms** [comment] 2016-06-28 22:31
I am following these threads with keen interest. Back in the day, I wrote a full regression test suite for the IGMPv3/MLDv2 control plane that wound up in Mac OS X. This was based on pexpect and made heavy use of serial port emulation, using Linux and FreeBSD kernels in QEMU, driving the BSD mtest binary as a test harness. I would hate to see this code bitrot.

**Comment by jhps** [comment] 2016-06-29 16:22
My code suffered bitrot via the apt-get route, as I suspect is the common case given that unix distribution maintainers will not give much thought to replacing a 3.x with a 4.x of the same library.
Given that, I suggest that if the breakage cannot be fixed easily then the refactoring should be reverted and only done in a renamed package. Failing that, issues should be raised with the distributions to use a different name for >=4.0. I don't know if there is a similar work-around with pip.

**Comment by takluyver** [comment] 2016-06-29 16:33
It's getting fixed in #359

**Comment by jquast** [comment] 2016-07-05 14:33
4.2.0 published to pypi with this fix

**Closed by jquast** 2016-07-05 14:33 UTC

**Comment by takluyver** [comment] 2016-07-05 14:37
Thanks @jquast - sorry I haven't been more responsive on this.

**Comment by jquast** [comment] 2016-07-05 18:25
no worries, have a great week!

**Comment by MountainRider** [comment] 2016-07-11 15:19
@jquast and @takluyver Thanks for helping me get this fix into the code.
