### ISSUE TITLE
send str loss a ~

### ISSUE THREAD

**Issue by flyl3una** [pexpect/pexpect#463] opened 2018-01-03 08:09 UTC
code
```
#! /usr/bin/python3

import pexpect

if __name__ == '__main__':
    connector = pexpect.spawn('ssh root@172.16.152.26')
    prompts_list = ["(?i)you sure you want to continue connecting",
                    "(?i)(password:)|(?:passphrase for key)",
                    "(?i)permission denied",
                    "(?i)terminal type",
                    pexpect.TIMEOUT,
                    "(?i)connection closed by remote host",
                    "(?i)Username:"]
    i = connector.expect(prompts_list)
    if i == 1:
        connector.sendline('6666')
    checklist = ['root@ubuntu:~# ',
                 pexpect.TIMEOUT,
                 pexpect.EOF]
    i = connector.expect(checklist)
    connector.sendline('LANG=zh_CN.utf8')
    checklist = ['root@ubuntu:~# ',
                 pexpect.TIMEOUT,
                 pexpect.EOF]
    i = connector.expect(checklist)
    connector.sendline('~~~123456')
    checklist = ['root@ubuntu:~# ',
                 '(?i)Enter new UNIX password: ',
                 '(?i)Retype new UNIX password: ',
                 pexpect.TIMEOUT,
                 pexpect.EOF]
    i = connector.expect(checklist, timeout=5)
    before = connector.before.decode('utf8')
    print(before)
```

print result:
```
~~123456
~~123456: command not found
```

**description**

I create a spawn and ssh connect remote computer. then use connector.send or sendline send my string to ssh connector. If it contain greater than or equal to two `~` at the beginning of the string. it can missing a `~`.

eg:
send: ~~~123456
recv:  ~~123456

my test env: 
pexpect 3.1 and 4.3.1
python2.6 and 3.6
system:centos7.2/6.5, ubuntu16.04, kali2016.1

> If I use telnet connect remote computer, the string haven't missing

**Comment by jquast** [comment] 2018-01-03 13:22
https://lonesysadmin.net/2011/11/08/ssh-escape-sequences-aka-kill-dead-ssh-sessions/

**Comment by jnatschev** [comment] 2018-01-04 04:04
hi.

the problem is not a pexpect problem. it is a ssh problem. the character tilde: ~. tilde is the ssh default escape key. you could try not using tildes in your string. if tildes are a must, then change the ssh escape key to another character using the ssh -e option:
ssh -e someothercharacter ...

alternatively you can have no escape sequence:
ssh -e none ...




Cheers,
John Natschev
‌

**Comment by jnatschev** [comment] 2018-01-04 04:05
oops. forgot one other bit, at your command line (assuming you are using a linux/unix os):
man ssh




Cheers,
John Natschev
‌

**Comment by flyl3una** [comment] 2018-01-04 09:58
thx~


I usually xshell open ssh connection, it can auto add escape characters.
Now, I can input escape characters in system console.

**Comment by takluyver** [comment] 2018-02-10 12:04
Closing because it doesn't sound like there's a pexpect bug here.

**Closed by takluyver** 2018-02-10 12:04 UTC
