### ISSUE TITLE
No typehinting

### ISSUE THREAD

**Issue by alxpettit** [pexpect/pexpect#706] opened 2021-12-11 00:22 UTC
Typehinting is very useful for projects that make use of the pexpect library -- catching errors during linting or with intellisense rather than during runtime.

Unfortunately, pexpect doesn't seem to have any typehinting. For instance, if I call `child.readline()`, PyCharm thinks it's a `str` rather than `bytes`, and erroneously precludes `decode()` from its suggestions.

Similarly, `child.match` doesn't have any intelligent None-safe coding suggestions, because it is not explicitly marked as an `Optional[re.Match]`. It's also noteworthy that autogenerated documentation can make use of typehints as well, and that would be a useful reference to those who prefer oldschool scripting without type safety. :P

**Comment by Red-M** [comment] 2021-12-11 05:22
If you'd like to submit a PR for this, I'm more than happy to review and merge it as long as others are ok with doing so, however, as a warning pexepect is a somewhat feature complete library and particularly stable so new features may take a while to be merged or may not be accepted at all due to breaking existing expected behaviour.

**Comment by alxpettit** [comment] 2021-12-11 13:45
I'd be willing to do that. This change actually wouldn't affect any code that uses `pexpect`, or at least, I don't see how it possibly could. Typehints are ignored by the interpreter itself. It is a tool for linting. See the opening statement [here](https://docs.python.org/3/library/typing.html). Honestly, it's basically a specialized code comment that's easy to parse.

It should also be noted that typehints in Python can track ambiguous typing, like for instance, things that might be `re.Match` or might be `None` can be marked as `Optional[re.Match]`. This means you can explicitly qualify your typing for the type checker without changing any of the logical behavior of the program.

The only way this could break something is that it causes annoying warnings for a project that is making use of an implicit conversion -- but if they're using that strict of a type checking system, they probably want to maximize their type safety anyway and would instead consider it a useful warning.

My biggest concern about making a PR is whether or not the team would feel comfortable maintaining that extra little bit of code. Like, what coding environments do ya'll typically use? Do you use a linter or type checker before your code goes to runtime testing?

Actually, thinking about it, the fact that your API is well established and you're not about to change around your arguments or return values kind of makes typehinting easier -- you don't have to worry much about accidentally leaving an old incorrect typehint, which is obviously worse than no typehint. :P

**Comment by Red-M** [comment] 2022-02-06 05:11
Personally, I use a text editor and none of this would help myself, nor would I use it.
If you're happy to release hinting either in a PR or via other means, please feel free to do so.

**Closed by Red-M** 2022-02-06 05:11 UTC
